feat: setup UI
Nemo-Git-Hub/ikra-website pull request #3
Opened 2022-10-31 14:22 UTC by Nemo-Git-Hub

# setup UI-kit

2022-11-04 13:04 UTC, LazurenkoNA requested changes
Rebase

2022-11-12 01:28 UTC, LazurenkoNA approved these changes

2022-11-12 01:28 UTC, LazurenkoNA commented on src/scss/_base.scss
> +  // font-weight: 400;кошка жрет как невменяемая.
:D

2022-11-12 08:17 UTC, Nemo-Git-Hub commented on src/scss/_base.scss
> +  // font-weight: 400;кошка жрет как невменяемая.
🤪

2022-11-12 08:17 UTC, merged